// Skills data
export const designSkills = [
  { name: "Adobe Photoshop", percentage: 95 },
  { name: "Adobe Illustrator", percentage: 90 },
  { name: "UI/UX Design", percentage: 85 },
  { name: "Figma", percentage: 80 },
];

export const mathSkills = [
  { name: "Calculus", percentage: 95 },
  { name: "Linear Algebra", percentage: 90 },
  { name: "Statistics", percentage: 85 },
  { name: "Curriculum Development", percentage: 90 },
];

export const dataSkills = [
  { name: "Python", percentage: 90 },
  { name: "Machine Learning", percentage: 85 },
  { name: "Data Visualization", percentage: 90 },
  { name: "SQL", percentage: 80 },
];

// Projects data
export const projects = [
  {
    id: 1,
    title: "Brand Identity & Logo Design",
    description: "Creative branding solutions and logo designs for various clients, focusing on unique visual identities.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-04.png",
    link: "#",
  },
  {
    id: 2,
    title: "Editorial Design",
    description: "Magazine layouts and editorial designs with modern typography and visual hierarchy.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-05.png",
    link: "#",
  },
  {
    id: 3,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-06.png",
    link: "#",
  },
  {
    id: 4,
    title: "Packaging Design",
    description: "Product packaging designs that combine aesthetics with practical functionality.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-08.png",
    link: "#",
  },
  {
    id: 5,
    title: "Motion Graphics",
    description: "Dynamic motion graphics and animations for digital platforms.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-09.png",
    link: "#",
  },
  {
    id: 6,
    title: "UI/UX Design",
    description: "User interface and experience design for web and mobile applications.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-10.png",
    link: "#",
  },
  {
    id: 7,
    title: "Data Visualization Design",
    description: "Interactive dashboard designs for analyzing and presenting complex data patterns.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-11.png",
    link: "#",
  },
  {
    id: 8,
    title: "Educational Design Materials",
    description: "Visually engaging educational materials and interactive learning resources.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-12.png",
    link: "#",
  },
  {
    id: 9,
    title: "Print Design",
    description: "Professional print materials including brochures, posters, and marketing collateral.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-13.png",
    link: "#",
  },
  {
    id: 10,
    title: "Digital Illustration",
    description: "Custom digital illustrations and artwork for various applications.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-14.png",
    link: "#",
  },
  {
    id: 11,
    title: "Analytics Dashboard Design",
    description: "User-friendly interface design for data analytics and visualization tools.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-15.png",
    link: "#",
  },
  {
    id: 12,
    title: "Interactive Learning Design",
    description: "Engaging visual design for digital educational resources and learning platforms.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-18.png",
    link: "#",
  },
  {
    id: 13,
    title: "Restaurant Menu Design",
    description: "Modern and elegant menu designs for upscale restaurants, featuring custom typography and food photography.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-19.png",
    link: "#",
  },
  {
    id: 14,
    title: "Instagram Story Templates",
    description: "Customizable social media templates for fashion and lifestyle brands, optimized for Instagram Stories.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-20.png",
    link: "#",
  },
  {
    id: 15,
    title: "Corporate Stationery Design",
    description: "Complete branding package including business cards, letterheads, and envelopes for corporate clients.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-21.png",
    link: "#",
  },
  {
    id: 16,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-22.png",
    link: "#",
  },
  {
    id: 17,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-23.png",
    link: "#",
  },
  {
    id: 18,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-24.png",
    link: "#",
  },
  {
    id: 19,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-25.png",
    link: "#",
  },
  {
    id: 20,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/GraphicDesing/portfolio-cover [Recovered]-26.png",
    link: "#",
  },
  {
    id: 21,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/GraphicDesing/portfolio-cover [Recovered]-28.png",
    link: "#",
  },
  {
    id: 22,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/GraphicDesing/portfolio-cover [Recovered]-29.png",
    link: "#",
  },
  {
    id: 23,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/GraphicDesing/portfolio-cover [Recovered]-30.png",
    link: "#",
  },
  {
    id: 24,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/GraphicDesing/portfolio-cover [Recovered]-31.png",
    link: "#",
  },
  {
    id: 25,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/GraphicDesing/portfolio-cover [Recovered]-32.png",
    link: "#",
  },
  {
    id: 26,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/GraphicDesing/portfolio-cover [Recovered]-33.png",
    link: "#",
  },
  {
    id: 29,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-35.png",
    link: "#",
  },
  {
    id: 30,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-36.png",
    link: "#",
  },
  {
    id:31,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-37.png",
    link: "#",
  },
  {
    id: 32,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-38.png",
    link: "#",
  },
  {
    id: 33,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-39.png",
    link: "#",
  },
  {
    id: 34,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-40.png",
    link: "#",
  },
  {
    id: 35,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-41.png",
    link: "#",
  },
  {
    id: 36,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-42.png",
    link: "#",
  },
  {
    id: 37,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-43.png",
    link: "#",
  },
  {
    id: 38,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-44.png",
    link: "#",
  },
  {
    id: 39,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-45.png",
    link: "#",
  },
  {
    id: 40,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-46.png",
    link: "#",
  },   
  {
    id: 41,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-47.png",
    link: "#",
  },
  {
    id: 42,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-48.png",
    link: "#",
  },
  {
    id: 43,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-49.png",
    link: "#",
  },
  {
    id: 44,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-50.png",
    link: "#",
  },
  {
    id: 45,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-51.png",
    link: "#",
  },
  {
    id: 46,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/GraphicDesing/portfolio-cover [Recovered]-52.png",
    link: "#",
  },
];

// Contact information
export const contactInfo = {
  email: "monkholmama123@gmail.com",
  phone: "0963098672",
  location: "Phnom Penh Cambodia",
  telegram: "https://t.me/MORK_Mongkul", 
  linkedin: "https://www.linkedin.com/in/mork-mongkul-2b622620b/", 
  github: "https://github.com/MORKMongkul ", 
}


// Social links
export const socialLinks = [
  { icon: "fab fa-linkedin-in", url: contactInfo.linkedin },
  { icon: "fab fa-github", url: contactInfo.github },
  { icon: "fab fa-telegram", url: contactInfo.telegram },
  { icon: "fab fa-behance", url: "#" },
];
