// Skills data
export const designSkills = [
  { name: "Adobe Photoshop", percentage: 95 },
  { name: "Adobe Illustrator", percentage: 90 },
  { name: "UI/UX Design", percentage: 85 },
  { name: "Figma", percentage: 80 },
];

export const mathSkills = [
  { name: "Calculus", percentage: 95 },
  { name: "Linear Algebra", percentage: 90 },
  { name: "Statistics", percentage: 85 },
  { name: "Curriculum Development", percentage: 90 },
];

export const dataSkills = [
  { name: "Python", percentage: 90 },
  { name: "Machine Learning", percentage: 85 },
  { name: "Data Visualization", percentage: 90 },
  { name: "SQL", percentage: 80 },
];

// Projects data
export const projects = [
  {
    id: 1,
    title: "Brand Identity & Logo Design",
    description: "Creative branding solutions and logo designs for various clients, focusing on unique visual identities.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-04.webp",
    link: "#",
  },
  {
    id: 2,
    title: "Editorial Design",
    description: "Magazine layouts and editorial designs with modern typography and visual hierarchy.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-05.webp",
    link: "#",
  },
  {
    id: 3,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-06.webp",
    link: "#",
  },
  {
    id: 4,
    title: "Packaging Design",
    description: "Product packaging designs that combine aesthetics with practical functionality.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-08.webp",
    link: "#",
  },
  {
    id: 5,
    title: "Motion Graphics",
    description: "Dynamic motion graphics and animations for digital platforms.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-09.webp",
    link: "#",
  },
  {
    id: 6,
    title: "UI/UX Design",
    description: "User interface and experience design for web and mobile applications.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-10.webp",
    link: "#",
  },
  {
    id: 7,
    title: "Data Visualization Design",
    description: "Interactive dashboard designs for analyzing and presenting complex data patterns.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-11.webp",
    link: "#",
  },
  {
    id: 8,
    title: "Educational Design Materials",
    description: "Visually engaging educational materials and interactive learning resources.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-12.webp",
    link: "#",
  },
  {
    id: 9,
    title: "Print Design",
    description: "Professional print materials including brochures, posters, and marketing collateral.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-13.webp",
    link: "#",
  },
  {
    id: 10,
    title: "Digital Illustration",
    description: "Custom digital illustrations and artwork for various applications.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-14.webp",
    link: "#",
  },
  {
    id: 11,
    title: "Analytics Dashboard Design",
    description: "User-friendly interface design for data analytics and visualization tools.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-15.webp",
    link: "#",
  },
  {
    id: 12,
    title: "Interactive Learning Design",
    description: "Engaging visual design for digital educational resources and learning platforms.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-18.webp",
    link: "#",
  },
  {
    id: 13,
    title: "Restaurant Menu Design",
    description: "Modern and elegant menu designs for upscale restaurants, featuring custom typography and food photography.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-19.webp",
    link: "#",
  },
  {
    id: 14,
    title: "Instagram Story Templates",
    description: "Customizable social media templates for fashion and lifestyle brands, optimized for Instagram Stories.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-20.webp",
    link: "#",
  },
  {
    id: 15,
    title: "Corporate Stationery Design",
    description: "Complete branding package including business cards, letterheads, and envelopes for corporate clients.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-21.webp",
    link: "#",
  },
  {
    id: 16,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-22.webp",
    link: "#",
  },
  {
    id: 17,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-23.webp",
    link: "#",
  },
  {
    id: 18,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-24.webp",
    link: "#",
  },
  {
    id: 19,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-25.webp",
    link: "#",
  },
  {
    id: 20,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-26.webp",
    link: "#",
  },
  {
    id: 21,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-28.webp",
    link: "#",
  },
  {
    id: 22,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-29.webp",
    link: "#",
  },
  {
    id: 23,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-30.webp",
    link: "#",
  },
  {
    id: 24,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-31.webp",
    link: "#",
  },
  {
    id: 25,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-32.webp",
    link: "#",
  },
  {
    id: 26,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-33.webp",
    link: "#",
  },
  {
    id: 29,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-35.webp",
    link: "#",
  },
  {
    id: 30,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-36.webp",
    link: "#",
  },
  {
    id:31,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-37.webp",
    link: "#",
  },
  {
    id: 32,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-38.webp",
    link: "#",
  },
  {
    id: 33,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-39.webp",
    link: "#",
  },
  {
    id: 34,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-40.webp",
    link: "#",
  },
  {
    id: 35,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-41.webp",
    link: "#",
  },
  {
    id: 36,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-42.webp",
    link: "#",
  },
  {
    id: 37,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-43.webp",
    link: "#",
  },
  {
    id: 38,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-44.webp",
    link: "#",
  },
  {
    id: 39,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-45.webp",
    link: "#",
  },
  {
    id: 40,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-46.webp",
    link: "#",
  },   
  {
    id: 41,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-47.webp",
    link: "#",
  },
  {
    id: 42,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-48.webp",
    link: "#",
  },
  {
    id: 43,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-49.webp",
    link: "#",
  },
  {
    id: 44,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-50.webp",
    link: "#",
  },
  {
    id: 45,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-51.webp",
    link: "#",
  },
  {
    id: 46,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-52.webp",
    link: "#",
  },
];

// Contact information
export const contactInfo = {
  email: "monkholmama123@gmail.com",
  phone: "0963098672",
  location: "Phnom Penh Cambodia",
  telegram: "https://t.me/MORK_Mongkul", 
  linkedin: "https://www.linkedin.com/in/mork-mongkul-2b622620b/", 
  github: "https://github.com/MORKMongkul ", 
}


// Social links
export const socialLinks = [
  { icon: "fab fa-linkedin-in", url: contactInfo.linkedin },
  { icon: "fab fa-github", url: contactInfo.github },
  { icon: "fab fa-telegram", url: contactInfo.telegram },
  { icon: "fab fa-behance", url: "#" },
];
