import { features } from "process";
import { IconType } from "react-icons";

// Define type for skills with optional icon
export interface Skill {
  name: string;
  percentage: number;
  icon?: IconType;
}

// Skills data
export const designSkills: Skill[] = [
  { name: "Adobe Photoshop", percentage: 95 },
  { name: "Adobe Illustrator", percentage: 90 },
  { name: "Adobe Premier", percentage: 85 },
  { name: "Adobe After Effects", percentage: 85 },
  { name: "Figma", percentage: 80 },
];

export const mathSkills: Skill[] = [
  { name: "Calculus", percentage: 95 },
  { name: "Linear Algebra", percentage: 90 },
  { name: "Statistics", percentage: 85 },
  { name: "Class Materials Design", percentage: 90 },
];

export const dataSkills: Skill[] = [
  { name: "Python", percentage: 90 },
  { name: "Machine Learning", percentage: 85 },
  { name: "Data Visualization", percentage: 90 },
  { name: "SQL", percentage: 80 },
  { name: "MySQL", percentage: 80 },
  { name: "PostgreSQL", percentage: 80 },
  { name: "Power BI", percentage: 85 },
];

// Projects data
export const projects = [
  {
    id: 1,
    title: "Brand Identity & Logo Design",
    description: "Creative branding solutions and logo designs for various clients, focusing on unique visual identities.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-04.webp",
    thumbnailImage: "/optimized-graphics/thumb-portfolio-cover [Recovered]-04.webp",
    link: "#",
    featured: true,
  },
  {
    id: 2,
    title: "Branding Identity & Logo Design",
    description: "Logo branding design for client from Home Sweet Home Furniture.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-05.webp",
    thumbnailImage: "/optimized-graphics/thumb-portfolio-cover [Recovered]-05.webp",
    link: "#",
  },
  {
    id: 3,
    title: "Logo Variation",
    description: "The logo variation, showing various types of logos on different branding color.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-06.webp",
    link: "#",
  },
  {
    id: 4,
    title: "Logo MockUp",
    description: "Logo mock up on different types of materials and evironment of the products and use cases.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-08.webp",
    link: "#",
  },
  {
    id: 5,
    title: "Business Card",
    description: "Business card, letter head of company showing the premium and use cases.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-09.webp",
    link: "#",
  },
  {
    id: 6,
    title: "T-shirt Mockup",
    description: "Showing a logo of company can be use on a real items that show a unique brand of the company.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-10.webp",
    link: "#",
  },
  {
    id: 7,
    title: "Company Website",
    description: "The use of logo on various digital of company website and online.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-11.webp",
    link: "#",
  },
  {
    id: 8,
    title: "logo Welcome 3D",
    description: "showing the real use case of logo as 3D logo on the wall.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-12.webp",
    link: "#",
  },
  {
    id: 9,
    title: "Print Ads",
    description: "The use of logo on advertisment and ads.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-13.webp",
    link: "#",
  },
  {
    id: 10,
    title: "Branding Identity & Logo Design",
    description: "This how a branding design are made with creativity, profficiency, that will able to bring the presense of the brand to the audience.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-14.webp",
    link: "#",
  },
  {
    id: 11,
    title: "3D welcome Logo",
    description: "Logo mock up of the wall of the company, showing a premium and unique",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-15.webp",
    link: "#",
  },
  {
    id: 12,
    title: "Various packaging Design",
    description: "The use cases of logo on various packaging products.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-18.webp",
    link: "#",
  },
  {
    id: 13,
    title: "Packaging Design",
    description: "Packaging design products of the company, showing how the logo was design and showing unique and identity of the brand.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-19.webp",
    link: "#",
  },
  {
    id: 14,
    title: "Premium Business Card",
    description: "A minimals premium business card.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-20.webp",
    link: "#",
  },
  {
    id: 15,
    title: "Billboard Ads",
    description: "Billboard advertisment, showing the glow of logo, easy to memorize.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-21.webp",
    link: "#",
  },
  {
    id: 16,
    title: "Blend Coffee Branding Identity ",
    description: "Branding design that inspire from the blend of the brands with its own products.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-22.webp",
    link: "#",
  },
  {
    id: 17,
    title: "Branding Items",
    description: "Showing the use cases of logo on various design and environemnt.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-23.webp",
    link: "#",
  },
  {
    id: 18,
    title: "Branding Items",
    description: "The use of logo on various type of products of the company.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-24.webp",
    link: "#",
  },
  {
    id: 19,
    title: "ID card Design",
    description: "A clean,minimal ID card showing the unique and premium of the Company.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-25.webp",
    link: "#",
  },
  {
    id: 20,
    title: "Cup Design",
    description: "Showing the real use of logo on the main product of the company.",
    category: "design",
    subcategory: "branding",
    image: "/optimized-graphics/portfolio-cover [Recovered]-26.webp",
    link: "#",
  },
  {
    id: 21,
    title: "Social Media Design",
    description: "Clean menu design for restuarant.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-28.webp",
    link: "#",
  },
  {
    id: 22,
    title: "Social Media Design",
    description: "A clean minimal menu of restuarant.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-29.webp",
    link: "#",
  },
  {
    id: 23,
    title: "Social Media Design",
    description: "A natural looks of X-stand for a coffee shop.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-30.webp",
    link: "#",
  },
  {
    id: 24,
    title: "Social Media Design",
    description: "An actual print X-stand ads for promoting new coffee menu.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-31.webp",
    link: "#",
  },
  {
    id: 25,
    title: "Social Media Design",
    description: "A big advertising banner for furniture compnany.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-32.webp",
    link: "#",
  },
  {
    id: 26,
    title: "Social Media Design",
    description: "A beautiful billboard advertising for Skin scare company.",
    category: "design",
    subcategory: "print",
    image: "/optimized-graphics/portfolio-cover [Recovered]-33.webp",
    link: "#",
  },
  {
    id: 29,
    title: "Social Media Design",
    description: "A collections of social media ads from various type of company.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-35.webp",
    link: "#",
  },
  {
    id: 30,
    title: "Social Media Design",
    description: "A dark glowing poster burger promotion poster.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-36.webp",
    link: "#",
  },
  {
    id:31,
    title: "Social Media Design",
    description: "A hot glowing pizza poster for domino pizza.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-37.webp",
    link: "#",
  },
  {
    id: 32,
    title: "Social Media Design",
    description: "New drink poster advertising poster.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-38.webp",
    link: "#",
  },
  {
    id: 33,
    title: "Social Media Design",
    description: "A promotion poster desing for KFC.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-39.webp",
    link: "#",
  },
  {
    id: 34,
    title: "Social Media Design",
    description: "A creative manipulation poster social media ads for delivery company .",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-40.webp",
    link: "#",
  },
  {
    id: 35,
    title: "Social Media Design",
    description: "A collection of drinking design poster ads.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-41.webp",
    link: "#",
  },
  {
    id: 36,
    title: "Social Media Design",
    description: "A simple, clean poster for daily post ads.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-42.webp",
    link: "#",
  },
  {
    id: 37,
    title: "Social Media Design",
    description: "A complete yellow poster, showing the brand of company and unique.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-43.webp",
    link: "#",
  },
  {
    id: 38,
    title: "Social Media Design",
    description: "A collection creative poster design .",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-44.webp",
    link: "#",
  },
  {
    id: 39,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-45.webp",
    link: "#",
  },
  {
    id: 40,
    title: "Social Media Design",
    description: "Engaging social media content and campaign designs for digital marketing.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-46.webp",
    link: "#",
  },   
  {
    id: 41,
    title: "Social Media Design",
    description: "A collection poster of national events in Cambodia.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-47.webp",
    link: "#",
  },
  {
    id: 42,
    title: "Social Media Design",
    description: "Pchum Ben poster design for Pchum Ben opening days.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-48.webp",
    link: "#",
  },
  {
    id: 43,
    title: "Social Media Design",
    description: "A poster of Pchum Ben first day.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-49.webp",
    link: "#",
  },
  {
    id: 44,
    title: "Social Media Design",
    description: "A collection of promotion poster from auto parts company.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-50.webp",
    link: "#",
  },
  {
    id: 45,
    title: "Social Media Design",
    description: "A collection of special events poster.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-51.webp",
    link: "#",
  },
  {
    id: 46,
    title: "Social Media Design",
    description: "A creative poster for Constitution Day of Cambodia.",
    category: "design",
    subcategory: "Social Media",
    image: "/optimized-graphics/portfolio-cover [Recovered]-52.webp",
    link: "#",
  },
  {
    id: 101,
    title: "Titanic Survival Prediction",
    description: "Machine learning model to predict survival on the Titanic using passenger data.",
    category: "data",
    subcategory: "machine_learning",
    image: "/optimized-graphics/Titanic_survival_prediction.webp",
    thumbnailImage: "/optimized-graphics/thumb-Titanic_survival_prediction.webp",
    link: "https://github.com/yourusername/titanic-survival-prediction",
    featured: true,
  },
  {
    id: 102,
    title: "Sentiment Analysis",
    description: "Natural language processing model for analyzing sentiment in text data.",
    category: "data",
    subcategory: "machine_learning",
    image: "/optimized-graphics/sentiment_analysis.webp",
    thumbnailImage: "/optimized-graphics/thumb-sentiment_analysis.webp",
    link: "https://github.com/yourusername/transformer-nlp",
    featured: true,
  },
  {
    id: 103,
    title: "Customer Churn Prediction",
    description: "Predictive analytics model to identify customers at risk of churning based on behavior patterns.",
    category: "data",
    subcategory: "machine_learning",
    image: "/optimized-graphics/customer_churn.webp",
    thumbnailImage: "/optimized-graphics/thumb-customer_churn.webp",
    link: "https://github.com/yourusername/customer-churn-prediction",
    featured: true,
  },
  {
    id: 110,
    title: "SAP Analytics Dashboard",
    description: "Interactive dashboards and data visualization using SAP Analytic Cloud.",
    category: "data",
    subcategory: "data_viz",
    image: "/optimized-graphics/thumb-Sap_analytic.webp",
    link: "https://aseandse.ap11.hcs.cloud.sap/sap/fpa/ui/tenants/2bd89/bo/story/BF60C802192D64C5A34C29D8B9FF3D7C",
    featured: true,
  },
  {
    id: 120,
    title: "Bike Rental System Design",
    description: "Designed a bike rental database with ER diagrams, SQL schema, sample data, and queries to manage rentals and customers.",
    category: "data",
    subcategory: "database",
    image: "/optimized-graphics/thumb-bike_rental_sys.webp",
    link: "https://github.com/MorkMongkul/Data-Science-Projects/tree/main/Bike_Rental_System_db",
    featured: false,
  },
];

// Contact information
export const contactInfo = {
  email: "monkholmama123@gmail.com",
  phone: "0963098672",
  location: "Phnom Penh Cambodia",
  telegram: "https://t.me/MORK_Mongkul", 
  linkedin: "https://www.linkedin.com/in/mork-mongkul-2b622620b/", 
  github: "https://github.com/MORKMongkul ", 
}

// Social links
export const socialLinks = [
  { icon: "fab fa-linkedin-in", url: contactInfo.linkedin },
  { icon: "fab fa-github", url: contactInfo.github },
  { icon: "fab fa-telegram", url: contactInfo.telegram },
  { icon: "fab fa-behance", url: "#" },
];
